# Global UPS variables. To be moved in a def file
REQUIRED_UHAL_VERSION = v2_6_0
UPS_QUALIFIERS ?= e14:prof:s50

PRODUCTNAME := protodune_timing

UPS_PACKAGE_VER_MAJOR = 0
UPS_PACKAGE_VER_MINOR = 1
UPS_PACKAGE_VER_PATCH = 0